DROP TABLE IF EXISTS player_ids;

CREATE TABLE player_ids (
    mfl_id INTEGER,
    sportradar_id TEXT,
    fantasypros_id INTEGER,
    gsis_id TEXT,
    pff_id INTEGER,
    sleeper_id INTEGER,
    nfl_id TEXT,
    espn_id INTEGER,
    yahoo_id INTEGER,
    fleaflicker_id INTEGER,
    cbs_id INTEGER,
    rotowire_id INTEGER,
    rotoworld_id INTEGER,
    ktc_id INTEGER,
    pfr_id TEXT,
    cfbref_id TEXT,
    stats_id INTEGER,
    stats_global_id INTEGER,
    fantasy_data_id INTEGER,
    swish_id INTEGER,
    name TEXT,
    merge_name TEXT,
    position TEXT,
    team TEXT,
    birthdate TEXT,
    age INTEGER,
    draft_year INTEGER,
    draft_round INTEGER,
    draft_pick INTEGER,
    draft_ovr INTEGER,
    twitter_username TEXT,
    height INTEGER,
    weight INTEGER,
    college TEXT,
    db_season INTEGER
);